# Site specific settings
title: "触手"
name: "TX187 Homepage"
keywords: "dev, anime, otaku, denpa, freak, gore"
baseurl: "/shokushuu"
url: "http://shokushuu.github.io"
description: "Personal site"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
twitter: tx187
github: shokushuu

# Build settings
markdown: kramdown
permalink: /:categories/:title/

theme: jekyll-theme-hacker